### ISSUE TITLE
Using empty hand when punching makes unbreakable think you've just broken a tool.

### ISSUE THREAD

**Issue by IMB11** [sylenthuntress/Unbreakable#3]
You can spam punch to stack the 3x knockback/other modifiers specified in settings. Punching does more damage than an iron sword in some cases lol

**Comment by sylenthuntress** [comment]
[Resolved](https://github.com/sylenthuntress/Unbreakable/commit/e4ba5f3497a6c1d4c30418d420ecd6dcd58540c4), seems like I had some misplaced brackets and a problematic condition that never came up in testing, I will push the fix next patch! ^^
